apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP # Um servi√ßo em que o ip nunca muda 
  selector:
    app: segundo-pod
  ports:
    - port: 9000
      targetPort: 80

#kubectl get services
#kubectl get svc

#rever moduilo 4 aula 4 